Systick example
hmightypirate/stm32f4discovery_examples pull request #2
Opened 2021-01-09 19:08 UTC by hmightypirate

2021-01-16 15:46 UTC, eLeDe commented on systick_src/hal/clock.c
> +  // FIXME: app dependent function
Remove this comment

2021-01-16 15:48 UTC, eLeDe commented on systick_src/main.c
> +void wait(void);
Wait function with nops is not needed anymore

2021-01-16 15:48 UTC, eLeDe commented on systick_src/main.c
> +    wait();
Remove wait function

2021-01-16 15:49 UTC, eLeDe requested changes
Wait function is not needed

2021-04-05 15:49 UTC, hmightypirate commented
Done

2021-04-05 15:49 UTC, merged